# Generated by Django 4.2.13 on 2024-06-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
