# Generated by Django 3.2.8 on 2024-06-08 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('source_file', models.FileField(upload_to='uploads/')),
                ('vocals_file', models.FileField(upload_to='uploads/')),
                ('backing_track_file', models.FileField(upload_to='uploads/')),
                ('tempo', models.IntegerField()),
                ('key', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracks',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
