# Generated by Django 3.2.8 on 2024-06-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='backing_track_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='key',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='vocals_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
