# Generated by Django 4.2.13 on 2024-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_track_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='track',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
